'use client';

import { useParams, useSearchParams } from 'next/navigation';
import { useEffect, useState, useMemo } from 'react';
import { doc, onSnapshot, collection, query, deleteDoc } from 'firebase/firestore';
import { useFirestore, useUser, useCollection, useMemoFirebase } from '@/firebase';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { ArrowLeft, Edit, UserPlus, Wallet, FileText, Download, Trash2, UploadCloud, Eye, Bot, Loader2 } from 'lucide-react';
import Link from 'next/link';
import { PropertyForm } from '@/components/dashboard/sales/property-form';
import { PropertyFinancials } from '@/components/dashboard/sales/property-financials';
import { PropertySetupBanner } from '@/components/dashboard/sales/property-setup-banner';
import {
  Dialog,
  DialogContent,
  DialogTrigger,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription
} from '@/components/ui/card';
import { FinancialPerformance } from '@/components/dashboard/financial-performance';
import { InviteTenantModal } from '@/components/tenants/InviteTenantModal';
import { RecordPaymentModal } from '@/components/dashboard/sales/RecordPaymentModal';
import { TenantDocumentUploader } from '@/components/tenants/TenantDocumentUploader';
import { useToast } from '@/hooks/use-toast';
import { deleteObject, ref } from 'firebase/storage';
import { useStorage } from '@/firebase';
import { generateLease } from '@/ai/flows/lease-flow';

function LeaseAgentModal({ tenant, propertyId, onOpenChange, isOpen }: { tenant: any, propertyId: string, isOpen: boolean, onOpenChange: (open: boolean) => void }) {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const { toast } = useToast();

  const handleConfirm = async () => {
    setLoading(true);
    try {
      // Assuming property state is available in the parent scope or fetched here.
      // For now, hardcoding 'TX' as per the user story.
      const flowResult = await generateLease({
        propertyId: propertyId,
        tenantId: tenant.id, // Assuming tenant object has an ID
        state: 'TX',
      });
      setResult(flowResult);
      toast({ title: 'Lease Sent!', description: 'The lease has been generated and sent for signature.' });
    } catch (error: any) {
      toast({ variant: 'destructive', title: 'Error', description: error.message });
    } finally {
      setLoading(false);
      onOpenChange(false); // Close the modal after action
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2"><Bot className="text-primary"/> AI Agent Confirmation</DialogTitle>
          <DialogDescription>
            Please review the AI's plan before proceeding.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4 py-4">
            <div className="bg-slate-50 p-4 rounded-lg border">
                <h4 className="font-semibold text-slate-800">Smart Summary</h4>
                <p className="text-sm text-slate-600 mt-1">
                    I have prepared a Texas-compliant lease for {tenant.firstName} {tenant.lastName}. I adjusted the security deposit return to 30 days and added the 2025 Flood Disclosure required for {propertyId}.
                </p>
            </div>
            <div>
                <h4 className="font-semibold text-slate-800">Legal Disclaimer</h4>
                <p className="text-xs text-muted-foreground mt-1">
                    This document was generated by an AI assistant. It is not a substitute for legal advice from a qualified attorney. Please review the document carefully before signing.
                </p>
            </div>
        </div>
        <DialogFooter>
          <Button variant="ghost" onClick={() => onOpenChange(false)}>Cancel</Button>
          <Button onClick={handleConfirm} disabled={loading} className="bg-primary hover:bg-primary/90">
            {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : null}
            Confirm & Send
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}


export default function PropertyDetailsPage() {
  const { id } = useParams();
  const searchParams = useSearchParams();
  const firestore = useFirestore();
  const { user } = useUser();
  const [property, setProperty] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isEditOpen, setIsEditOpen] = useState(false);
  const [isInviteOpen, setIsInviteOpen] = useState(false);
  const [isLeaseAgentOpen, setLeaseAgentOpen] = useState(false);
  const [selectedTenantForLease, setSelectedTenantForLease] = useState<any>(null);


  const defaultTab = searchParams.get('tab') || 'overview';
  const [formTab, setFormTab] = useState('general');

  useEffect(() => {
    if (!firestore || !id) return;

    const docRef = doc(firestore, 'properties', id as string);

    const unsubscribe = onSnapshot(docRef, (docSnap) => {
      if (docSnap.exists()) {
        setProperty({ id: docSnap.id, ...docSnap.data() });
      } else {
        setProperty(null);
      }
      setIsLoading(false);
    }, (error) => {
      console.error("Error fetching property:", error);
      setIsLoading(false);
    });

    return () => unsubscribe();
  }, [firestore, id]);

  const handleOpenDialog = (tab: string) => {
    setFormTab(tab);
    setIsEditOpen(true);
  }

  const handleOpenLeaseAgent = (tenant: any) => {
    setSelectedTenantForLease(tenant);
    setLeaseAgentOpen(true);
  };


  if (isLoading || !user) return <div className="p-8 text-muted-foreground">Loading property details...</div>;
  if (!property) return <div className="p-8">Property not found.</div>;

  return (
    <>
      <div className="space-y-6 p-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link href="/dashboard/properties">
              <Button variant="ghost" size="icon"><ArrowLeft className="h-4 w-4" /></Button>
            </Link>
            <div>
              <h1 className="text-2xl font-bold">{property.name}</h1>
              <p className="text-muted-foreground">{property.address.street}, {property.address.city}</p>
            </div>
          </div>

          <Dialog open={isEditOpen} onOpenChange={setIsEditOpen}>
            <DialogTrigger asChild>
              <Button variant="outline" onClick={() => handleOpenDialog('general')}><Edit className="mr-2 h-4 w-4" /> Edit Settings</Button>
            </DialogTrigger>
            <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
              <DialogHeader>
                <DialogTitle>Edit Property Settings</DialogTitle>
                <DialogDescription>
                  Update tenants, mortgage details, and configuration for {property.name}.
                </DialogDescription>
              </DialogHeader>
              <PropertyForm initialData={{ id: property.id, ...property }} onSuccess={() => setIsEditOpen(false)} defaultTab={formTab} />
            </DialogContent>
          </Dialog>
        </div>

        <FinancialPerformance propertyId={id as string} />

        <PropertySetupBanner
          propertyId={id as string}
          propertyData={property}
          onOpenSettings={handleOpenDialog}
        />

        <Tabs defaultValue={defaultTab} className="w-full">
          <TabsList className="grid w-full grid-cols-5 lg:w-[750px]">
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="tenants">Tenants</TabsTrigger>
            <TabsTrigger value="documents">Documents</TabsTrigger>
            <TabsTrigger value="financials">Expenses</TabsTrigger>
            <TabsTrigger value="leases">Lease Summary</TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="mt-6">
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
              <Card>
                <CardHeader className="pb-2">
                  <CardDescription>Mortgage Principal</CardDescription>
                  <CardTitle className="text-2xl font-bold">$1,050.96</CardTitle>
                </CardHeader>
              </Card>
              <Card>
                 <CardHeader className="pb-2">
                  <CardDescription>Mortgage Interest</CardDescription>
                  <CardTitle className="text-2xl font-bold">$1,032.70</CardTitle>
                </CardHeader>
              </Card>
              <Card>
                <CardHeader className="pb-2">
                  <CardDescription>Status</CardDescription>
                  <CardTitle className="text-2xl font-bold capitalize">
                    {property.tenants && property.tenants.length > 0 ? 'Occupied' : 'Vacant'}
                  </CardTitle>
                </CardHeader>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="tenants" className="mt-6">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between">
                <div>
                  <CardTitle>Current Residents</CardTitle>
                  <CardDescription>Lease details for this property.</CardDescription>
                </div>
                <div className="flex items-center gap-2">
                  <Button variant="outline" size="sm" onClick={() => handleOpenDialog('tenants')}>Manage Tenants</Button>
                  <Button size="sm" onClick={() => setIsInviteOpen(true)} className="gap-2">
                    <UserPlus className="h-4 w-4" /> Invite
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                {property.tenants && property.tenants.length > 0 ? (
                  <div className="space-y-4">
                    {property.tenants.map((t: any, i: number) => (
                      <div key={i} className="flex justify-between items-center border-b pb-4 last:border-0 last:pb-0">
                        <div>
                          <p className="font-medium">{t.firstName} {t.lastName}</p>
                          <p className="text-sm text-muted-foreground">{t.email}</p>
                        </div>
                        <div className="text-right">
                          <p className="font-medium">${t.rentAmount}/mo</p>
                          <p className="text-xs text-muted-foreground">Lease ends: {t.leaseEnd || 'N/A'}</p>
                        </div>
                        <div className="flex items-center gap-2">
                            <RecordPaymentModal
                                tenant={t}
                                propertyId={property.id}
                                landlordId={user.uid}
                            />
                            <Button variant="outline" size="sm" onClick={() => handleOpenLeaseAgent(t)} className="gap-1">
                                <Bot className="h-4 w-4"/> Auto-Draft Lease
                            </Button>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-muted-foreground text-sm">No tenants recorded. Click "Invite" to add one.</p>
                )}
              </CardContent>
            </Card>
          </TabsContent>
          
          <TabsContent value="documents" className="mt-6">
              <PropertyDocuments propertyId={id as string} landlordId={user.uid} />
          </TabsContent>

          <TabsContent value="financials" className="mt-6">
            <PropertyFinancials
              propertyId={property.id}
              propertyName={property.name}
              view="expenses"
            />
          </TabsContent>

          <TabsContent value="leases" className="mt-6">
             <div className="text-center py-10 border-2 border-dashed rounded-lg">
                <FileText className="h-10 w-10 mx-auto text-slate-300 mb-2"/>
                <p className="text-sm text-muted-foreground">Lease summary and key clauses will be displayed here.</p>
            </div>
          </TabsContent>
        </Tabs>
      </div>

      {isInviteOpen && (
        <InviteTenantModal
          isOpen={isInviteOpen}
          onOpenChange={setIsInviteOpen}
          propertyId={property.id}
          landlordId={user.uid}
        />
      )}
      {isLeaseAgentOpen && selectedTenantForLease && (
        <LeaseAgentModal
            isOpen={isLeaseAgentOpen}
            onOpenChange={setLeaseAgentOpen}
            tenant={selectedTenantForLease}
            propertyId={property.id}
        />
      )}
    </>
  );
}


function PropertyDocuments({ propertyId, landlordId }: { propertyId: string, landlordId: string}) {
  const firestore = useFirestore();
  const storage = useStorage();
  const { toast } = useToast();
  const [isUploaderOpen, setUploaderOpen] = useState(false);

  const docsQuery = useMemoFirebase(() => {
    if (!firestore || !propertyId) return null;
    return query(collection(firestore, `properties/${propertyId}/documents`));
  }, [firestore, propertyId]);

  const { data: documents, isLoading } = useCollection(docsQuery);

  const handleDelete = async (docData: any) => {
    if (!docData?.storagePath) {
        toast({ variant: 'destructive', title: 'Cannot Delete', description: 'Document metadata is missing storage path.' });
        return;
    }
    if (!confirm(`Are you sure you want to delete ${docData.fileName}?`)) return;

    try {
        // Delete from Storage
        const fileRef = ref(storage, docData.storagePath);
        await deleteObject(fileRef);

        // Delete from Firestore
        const docRef = doc(firestore, `properties/${propertyId}/documents`, docData.id);
        await deleteDoc(docRef);

        toast({ title: 'Document Deleted', description: `${docData.fileName} has been removed.` });
    } catch (error: any) {
        console.error("Deletion Error:", error);
        toast({ variant: 'destructive', title: 'Deletion Failed', description: error.message });
    }
  };

  return (
    <>
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <CardTitle>Document Storage</CardTitle>
            <CardDescription>Lease agreements, inspection reports, and other files for this property.</CardDescription>
          </div>
          <Button size="sm" onClick={() => setUploaderOpen(true)} className="gap-2">
            <UploadCloud className="h-4 w-4" /> Upload File
          </Button>
        </CardHeader>
        <CardContent>
          {isLoading && <p>Loading documents...</p>}
          {!isLoading && (!documents || documents.length === 0) && (
            <div className="text-center py-10 border-2 border-dashed rounded-lg">
                <FileText className="h-10 w-10 mx-auto text-slate-300 mb-2"/>
                <p className="text-sm text-muted-foreground">No documents uploaded for this property yet.</p>
            </div>
          )}
          {!isLoading && documents && documents.length > 0 && (
            <div className="space-y-3">
              {documents.map((doc: any) => (
                <div key={doc.id} className="flex items-start justify-between p-3 bg-slate-50 border rounded-md">
                  <div>
                    <p className="font-medium">{doc.fileName}</p>
                    <p className="text-xs text-muted-foreground mt-1">Type: {doc.fileType} | Uploaded: {new Date(doc.uploadedAt?.seconds * 1000).toLocaleDateString()}</p>
                    {doc.description && <p className="text-sm text-slate-600 mt-2 pl-2 border-l-2 border-slate-200">{doc.description}</p>}
                  </div>
                  <div className="flex items-center gap-2">
                    <a href={doc.downloadUrl} target="_blank" rel="noopener noreferrer">
                      <Button variant="outline" size="sm" className="gap-1"><Eye className="h-3 w-3"/> View</Button>
                    </a>
                    <a href={doc.downloadUrl} download>
                      <Button variant="outline" size="sm" className="gap-1"><Download className="h-3 w-3"/> Download</Button>
                    </a>
                    <Button variant="ghost" size="icon" className="h-8 w-8 text-red-500 hover:bg-red-50" onClick={() => handleDelete(doc)}>
                        <Trash2 className="h-4 w-4"/>
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
      {isUploaderOpen && (
        <TenantDocumentUploader
          isOpen={isUploaderOpen}
          onOpenChange={setUploaderOpen}
          propertyId={propertyId}
          landlordId={landlordId}
        />
      )}
    </>
  )
}

    
