

'use client';

import { useState, useMemo } from 'react';
import { doc, collection, query, deleteDoc } from 'firebase/firestore';
import { useFirestore, useUser, useCollection, useMemoFirebase } from '@/firebase';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { ArrowLeft, Edit, UserPlus, Wallet, FileText, Download, Trash2, UploadCloud, Eye, Bot, Loader2, BookOpen, HandCoins } from 'lucide-react';
import Link from 'next/link';
import { PropertyForm } from '@/components/dashboard/sales/property-form';
import { PropertyFinancials } from '@/components/dashboard/sales/property-financials';
import { PropertySetupBanner } from '@/components/dashboard/sales/property-setup-banner';
import {
  Dialog,
  DialogContent,
  DialogTrigger,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription
} from '@/components/ui/card';
import { FinancialPerformance } from '@/components/dashboard/financial-performance';
import { InviteTenantModal } from '@/components/tenants/InviteTenantModal';
import { RecordPaymentModal } from '@/components/dashboard/sales/RecordPaymentModal';
import { TenantDocumentUploader } from '@/components/tenants/TenantDocumentUploader';
import { useToast } from '@/hooks/use-toast';
import { useStorage } from '@/firebase';
import { generateLease } from '@/ai/flows/lease-flow';
import { formatCurrency } from '@/lib/format';
import { ref, deleteObject } from 'firebase/storage';
import { isPast, parseISO } from 'date-fns';


function LeaseAgentModal({ tenant, propertyId, onOpenChange, isOpen }: { tenant: any, propertyId: string, isOpen: boolean, onOpenChange: (open: boolean) => void }) {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const { toast } = useToast();

  const handleConfirm = async () => {
    setLoading(true);
    try {
      const flowResult = await generateLease({
        propertyId: propertyId,
        tenantId: tenant.email, 
        state: 'TX',
      });
      setResult(flowResult);
      toast({ title: 'Lease Saved!', description: 'The lease has been generated and saved to your documents tab.' });
    } catch (error: any) {
      toast({ variant: 'destructive', title: 'Error', description: error.message });
    } finally {
      setLoading(false);
      onOpenChange(false); // Close the modal after action
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2"><Bot className="text-primary"/> AI Agent Confirmation</DialogTitle>
          <DialogDescription>
            Please review the AI's plan before proceeding.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4 py-4">
            <div className="bg-slate-50 p-4 rounded-lg border">
                <h4 className="font-semibold text-slate-800">Smart Summary</h4>
                <p className="text-sm text-slate-600 mt-1">
                    I will generate a Texas-compliant lease for {tenant.firstName} {tenant.lastName} and save it to this property's documents tab.
                </p>
            </div>
            <div>
                <h4 className="font-semibold text-slate-800">Legal Disclaimer</h4>
                <p className="text-xs text-muted-foreground mt-1">
                    This document was generated by an AI assistant. It is not a substitute for legal advice from a qualified attorney. Please review the document carefully before signing.
                </p>
            </div>
        </div>
        <DialogFooter>
          <Button variant="ghost" onClick={() => onOpenChange(false)}>Cancel</Button>
          <Button onClick={handleConfirm} disabled={loading} className="bg-primary hover:bg-primary/90">
            {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : null}
            Confirm & Generate
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}


export function PropertyDashboardSFH({ property, onUpdate }: { property: any, onUpdate: () => void }) {
  const [isEditOpen, setIsEditOpen] = useState(false);
  const [isInviteOpen, setIsInviteOpen] = useState(false);
  const [isLeaseAgentOpen, setLeaseAgentOpen] = useState(false);
  const [selectedTenantForLease, setSelectedTenantForLease] = useState<any>(null);

  const [formTab, setFormTab] = useState('general');

  const handleOpenDialog = (tab: string) => {
    setFormTab(tab);
    setIsEditOpen(true);
  }

  const handleOpenLeaseAgent = (tenant: any) => {
    setSelectedTenantForLease({...tenant });
    setLeaseAgentOpen(true);
  };
  
  const { user } = useUser();
  if (!user) return <div className="p-8 text-muted-foreground">Loading...</div>;
  if (!property) return <div className="p-8">Property not found.</div>;
  
  const getPropertyStatus = () => {
    const activeTenant = property.tenants?.find((t: any) => t.status === 'active');
    if (!activeTenant) return 'Vacant';
    if (activeTenant.leaseEnd && isPast(parseISO(activeTenant.leaseEnd))) {
      return 'Lease Expired';
    }
    return 'Occupied';
  };

  const status = getPropertyStatus();
  const activeTenant = property.tenants?.find((t: any) => t.status === 'active');
  const rentAmount = activeTenant ? activeTenant.rentAmount : (property.financials?.targetRent || 0);

  
  const header = (
    <div className="flex items-center justify-between">
      <div className="flex items-center gap-4">
        <Link href="/dashboard/properties">
          <Button variant="ghost" size="icon"><ArrowLeft className="h-4 w-4" /></Button>
        </Link>
        <div>
          <h1 className="text-2xl font-bold">{property.name}</h1>
          <p className="text-muted-foreground">{property.address.street}, {property.address.city}</p>
        </div>
      </div>
      <div className="flex items-center gap-2">
        <Dialog open={isEditOpen} onOpenChange={setIsEditOpen}>
            <DialogTrigger asChild>
            <Button variant="outline" onClick={() => handleOpenDialog('general')}><Edit className="mr-2 h-4 w-4" /> Edit Settings</Button>
            </DialogTrigger>
            <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
                <DialogTitle>Edit Property Settings</DialogTitle>
                <DialogDescription>
                Update tenants, mortgage details, and configuration for {property.name}.
                </DialogDescription>
            </DialogHeader>
            <PropertyForm 
                initialData={{ id: property.id, ...property }} 
                onSuccess={() => { onUpdate(); setIsEditOpen(false); }} 
                defaultTab={formTab} 
            />
            </DialogContent>
        </Dialog>
      </div>
    </div>
  );

  return (
    <>
      <div className="space-y-6 p-6">
        {header}

        <FinancialPerformance propertyId={property.id} viewingDate={new Date()} />

        <PropertySetupBanner
          propertyId={property.id}
          propertyData={property}
          onOpenSettings={handleOpenDialog}
        />

        <Tabs defaultValue="overview" className="w-full">
          <TabsList className="grid w-full grid-cols-6 lg:w-[850px]">
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="tenants">Tenants</TabsTrigger>
            <TabsTrigger value="income">Income</TabsTrigger>
            <TabsTrigger value="expenses">Expenses</TabsTrigger>
            <TabsTrigger value="deposits">Deposits</TabsTrigger>
            <TabsTrigger value="documents">Documents</TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="mt-6">
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
              <Card>
                <CardHeader className="pb-2">
                  <CardDescription>Principal & Interest</CardDescription>
                  <CardTitle className="text-2xl font-bold">
                    {formatCurrency(property.mortgage?.principalAndInterest || 0)}
                  </CardTitle>
                </CardHeader>
              </Card>
              <Card>
                 <CardHeader className="pb-2">
                  <CardDescription>Current Rent</CardDescription>
                  <CardTitle className="text-2xl font-bold">
                    {formatCurrency(rentAmount)}
                  </CardTitle>
                </CardHeader>
              </Card>
              <Card>
                <CardHeader className="pb-2">
                  <CardDescription>Status</CardDescription>
                  <CardTitle className="text-2xl font-bold capitalize">
                    {status}
                  </CardTitle>
                </CardHeader>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="tenants" className="mt-6">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between">
                <div>
                  <CardTitle>Current Residents</CardTitle>
                  <CardDescription>Lease details for this property.</CardDescription>
                </div>
                <div className="flex items-center gap-2">
                  <Button variant="outline" size="sm" onClick={() => handleOpenDialog('tenants')}>Manage Tenants</Button>
                  <Button size="sm" onClick={() => setIsInviteOpen(true)} className="gap-2">
                    <UserPlus className="h-4 w-4" /> Create Portal
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                {property.tenants && property.tenants.length > 0 ? (
                  <div className="space-y-4">
                    {property.tenants.map((t: any, i: number) => (
                      <div key={i} className="flex justify-between items-center border-b pb-4 last:border-0 last:pb-0">
                        <div>
                          <p className="font-medium">{t.firstName} {t.lastName}</p>
                          <p className="text-sm text-muted-foreground">{t.email}</p>
                        </div>
                        <div className="text-right">
                          <p className="font-medium">${(t.rentAmount || 0).toLocaleString()}/mo</p>
                          <p className="text-xs text-muted-foreground">Lease ends: {t.leaseEnd || 'N/A'}</p>
                        </div>
                        <div className="flex items-center gap-2">
                            <RecordPaymentModal
                                tenant={{...t, id: t.email || `tenant_${i}`}} // Ensure a unique ID
                                propertyId={property.id}
                                landlordId={user.uid}
                                onSuccess={onUpdate}
                            />
                            <Button variant="outline" size="sm" onClick={() => handleOpenLeaseAgent(t)} className="gap-1">
                                <Bot className="h-4 w-4"/> Auto-Draft Lease
                            </Button>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-muted-foreground text-sm">No tenants recorded. Click "Create Portal" to add one.</p>
                )}
              </CardContent>
            </Card>
          </TabsContent>
          
          <TabsContent value="income" className="mt-6">
            <PropertyFinancials
              propertyId={property.id}
              propertyName={property.name}
              view="income"
            />
          </TabsContent>
          
          <TabsContent value="expenses" className="mt-6">
            <PropertyFinancials
              propertyId={property.id}
              propertyName={property.name}
              view="expenses"
            />
          </TabsContent>

          <TabsContent value="deposits" className="mt-6">
            <PropertyFinancials
              propertyId={property.id}
              propertyName={property.name}
              view="deposits"
            />
          </TabsContent>

          <TabsContent value="documents" className="mt-6">
              <PropertyDocuments propertyId={property.id} landlordId={user.uid} />
          </TabsContent>
        </Tabs>
      </div>

      {isInviteOpen && (
        <InviteTenantModal
          isOpen={isInviteOpen}
          onOpenChange={setIsInviteOpen}
          propertyId={property.id}
          landlordId={user.uid}
        />
      )}
      {isLeaseAgentOpen && selectedTenantForLease && (
        <LeaseAgentModal
            isOpen={isLeaseAgentOpen}
            onOpenChange={setLeaseAgentOpen}
            tenant={selectedTenantForLease}
            propertyId={property.id}
        />
      )}
    </>
  );
}


function PropertyDocuments({ propertyId, landlordId }: { propertyId: string, landlordId: string}) {
  const firestore = useFirestore();
  const storage = useStorage();
  const { toast } = useToast();
  const [isUploaderOpen, setUploaderOpen] = useState(false);
  const [isDeleting, setIsDeleting] = useState<string | null>(null);

  const docsQuery = useMemoFirebase(() => {
    if (!firestore || !propertyId) return null;
    return query(collection(firestore, `properties/${propertyId}/documents`));
  }, [firestore, propertyId]);

  const { data: documents, isLoading, refetch: refetchDocs } = useCollection(docsQuery);

  const handleDelete = async (docData: any) => {
    if (!firestore || !storage) {
        toast({ variant: 'destructive', title: 'Error', description: 'Firebase services not available.' });
        return;
    }

    let fileRef;
    if (docData?.storagePath) {
        fileRef = ref(storage, docData.storagePath);
    } else if (docData?.downloadUrl) {
        fileRef = ref(storage, docData.downloadUrl);
    } else {
        toast({ variant: 'destructive', title: 'Cannot Delete', description: 'No file path found in document.' });
        return;
    }

    try {
        await deleteObject(fileRef);
        
        const docRef = doc(firestore, `properties/${propertyId}/documents`, docData.id);
        await deleteDoc(docRef);

        toast({ title: 'Document Deleted', description: `${docData.fileName} removed successfully.` });
        refetchDocs();
    } catch (error: any) {
        console.error("Deletion Error:", error);
        if (error.code === 'storage/object-not-found') {
             const docRef = doc(firestore, `properties/${propertyId}/documents`, docData.id);
             await deleteDoc(docRef);
             toast({ title: 'Cleaned Up', description: 'File was missing from storage, so database record was removed.' });
             refetchDocs();
        } else if (error.code === 'storage/unauthorized') {
            toast({ variant: 'destructive', title: 'Permission Denied', description: 'You do not have permission to delete this file.' });
        } else {
            toast({ variant: 'destructive', title: 'Deletion Failed', description: error.message });
        }
    }
  };

  const getSafeDate = (timestamp: any) => {
    if (!timestamp) return 'N/A';
    if (typeof timestamp === 'string') {
        const date = new Date(timestamp);
        if (!isNaN(date.getTime())) {
            return date.toLocaleDateString();
        }
    }
    if (timestamp.seconds) {
      return new Date(timestamp.seconds * 1000).toLocaleDateString();
    }
    try {
      const date = new Date(timestamp);
      if (isNaN(date.getTime())) return 'Invalid Date';
      return date.toLocaleDateString();
    } catch (e) {
      return 'Invalid Date';
    }
  };

  const onUploadSuccess = () => {
    refetchDocs();
    setUploaderOpen(false);
  }

  return (
    <>
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <CardTitle>Document Storage</CardTitle>
            <CardDescription>Lease agreements, inspection reports, and other files for this property.</CardDescription>
          </div>
          <Button size="sm" onClick={() => setUploaderOpen(true)} className="gap-2">
            <UploadCloud className="h-4 w-4" /> Upload File
          </Button>
        </CardHeader>
        <CardContent>
          {isLoading && <p>Loading documents...</p>}
          {!isLoading && (!documents || documents.length === 0) && (
            <div className="text-center py-10 border-2 border-dashed rounded-lg">
                <FileText className="h-10 w-10 mx-auto text-slate-300 mb-2"/>
                <p className="text-sm text-muted-foreground">No documents uploaded for this property yet.</p>
            </div>
          )}
          {!isLoading && documents && documents.length > 0 && (
            <div className="space-y-3">
              {documents.map((doc: any) => (
                <div key={doc.id} className="flex items-start justify-between p-3 bg-slate-50 border rounded-md">
                  <div>
                    <p className="font-medium">{doc.fileName}</p>
                    <p className="text-xs text-muted-foreground mt-1">Type: {doc.fileType} | Uploaded: {getSafeDate(doc.uploadedAt)}</p>
                    {doc.description && <p className="text-sm text-slate-600 mt-2 pl-2 border-l-2 border-slate-200">{doc.description}</p>}
                  </div>
                  <div className="flex items-center gap-1">
                    <a href={doc.downloadUrl} target="_blank" rel="noopener noreferrer">
                      <Button variant="outline" size="sm" className="gap-1"><Eye className="h-3 w-3"/> View</Button>
                    </a>
                    <a href={doc.downloadUrl} download>
                      <Button variant="outline" size="sm" className="gap-1"><Download className="h-3 w-3"/> Download</Button>
                    </a>
                    
                    {isDeleting === doc.id ? (
                        <Button 
                            variant="destructive" 
                            size="sm" 
                            onClick={() => {
                                handleDelete(doc);
                                setIsDeleting(null);
                            }}
                        >
                            Confirm Delete?
                        </Button>
                    ) : (
                        <Button variant="ghost" size="icon" className="h-8 w-8 text-red-500 hover:bg-red-50" onClick={() => setIsDeleting(doc.id)}>
                            <Trash2 className="h-4 w-4"/>
                        </Button>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
      {isUploaderOpen && (
        <TenantDocumentUploader
          isOpen={isUploaderOpen}
          onOpenChange={setUploaderOpen}
          propertyId={propertyId}
          landlordId={landlordId}
          onSuccess={onUploadSuccess}
        />
      )}
    </>
  )
}
