
import { Header } from '@/components/marketing/Header';
import { Footer } from '@/components/marketing/Footer';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { AlertTriangle } from 'lucide-react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Disclaimer | OmidanLedger',
    description: 'Important disclaimers regarding the use of OmidanLedger for financial decisions.',
};


export default function DisclaimerPage() {
  return (
    <div className="bg-slate-50 min-h-screen flex flex-col">
      <Header />
      <main className="flex-1 py-20 px-4">
        <div className="container mx-auto max-w-3xl">
          <Card className="shadow-lg">
            <CardHeader className="text-center p-8">
               <AlertTriangle className="h-12 w-12 text-amber-500 mx-auto mb-4" />
              <CardTitle className="text-4xl font-bold tracking-tight text-slate-900">
                Disclaimer
              </CardTitle>
               <CardDescription>
                Last updated: {new Date().toLocaleDateString()}
              </CardDescription>
            </CardHeader>
            <CardContent className="px-8 pb-8 space-y-8 text-slate-700">

               <Alert variant="destructive" className="bg-red-50 border-red-200 text-red-900">
                  <AlertTriangle className="h-4 w-4" />
                  <AlertTitle className="font-bold">Please Read Carefully</AlertTitle>
                  <AlertDescription>
                    Your use of this application is subject to the following disclaimers.
                  </AlertDescription>
              </Alert>

              <div className="space-y-2">
                <h2 className="text-2xl font-semibold">Not Financial or Legal Advice</h2>
                <p>
                  OmidanLedger is a financial information tool and is not intended to provide legal, tax, or financial advice. The information and reports generated by the application are for informational purposes only. You should consult with a professional accountant, financial advisor, or attorney for advice specific to your situation.
                </p>
              </div>

               <div className="space-y-2">
                <h2 className="text-2xl font-semibold">Accuracy of Information</h2>
                <p>
                  While we strive to provide accurate and up-to-date information, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the application. Automated categorization may not always be correct and should be reviewed.
                </p>
              </div>

               <div className="space-y-2">
                <h2 className="text-2xl font-semibold">Use at Your Own Risk</h2>
                <p>
                  Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the application or reliance on any information provided. Your use of OmidanLedger and your reliance on any information on the application is solely at your own risk.
                </p>
              </div>

              <div className="text-center pt-6 border-t">
                <p className="text-muted-foreground">
                  Questions? Email us at <a href="mailto:support@omidanledger.com" className="text-primary font-medium hover:underline">support@omidanledger.com</a>
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
      <Footer />
    </div>
  );
}
